export const USER_INFORMATION = [
  {
    name: "Liam Johnson",
    mail: "liamjohnson@example.com",
    role: "Sale",
    status: "Fulfilled",
    date: "2023-06-23",
    price: "$250.00",
  },
  {
    name: "Olivia Smith",
    mail: "olivia@example.com",
    role: "Refund",
    status: "Declined",
    date: "2023-06-24",
    price: "$150.00",
  },
  {
    name: "Noah Williams",
    mail: "noah@example.com",
    role: "Subscription",
    status: "Fulfilled",
    date: "2023-06-25",
    price: "$350.00",
  },
  {
    name: "Emma Brown",
    mail: "emma@example.com",
    role: "Sale",
    status: "Fulfilled",
    date: "2023-06-26",
    price: "$450.00",
  },
  {
    name: "Liam Harry",
    mail: "harry@example.com",
    role: "Sale",
    status: "Fulfilled",
    date: "2023-06-23",
    price: "$250.00",
  },
  {
    name: "Liam Johnson2",
    mail: "liam@example2.com",
    role: "Sale",
    status: "Fulfilled",
    date: "2023-06-23",
    price: "$250.00",
  },
  {
    name: "Olivia Smith2",
    mail: "olivia@example2.com",
    role: "Refund",
    status: "Declined",
    date: "2023-06-24",
    price: "$150.00",
  },
  {
    name: "Emma Brown2",
    mail: "emma@example2.com",
    role: "Sale",
    status: "Fulfilled",
    date: "2023-06-26",
    price: "$450.00",
  },
];
